name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: test-reports/

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v3

    - name: Build the Project
      run: |
        echo "Building the project..."
        
    - name: Upload Build Package
      uses: actions/upload-artifact@v3
      with:
        name: build-package
        path: dist/

  notify:
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Send Notification Email
      run: python send_email.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }} 
