name: CI/CD S106
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run'
        required: true
        default: 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s tests
    
    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Package
      run: zip -r package.zip ./

    - name: Upload Build Package
      uses: actions/upload-artifact@v3
      with:
        name: build-package
        path: package.zip

    notify:
    needs: [tests, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Instala o Python e dependências
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Instala dependências se necessário
    - name: Install dependencies
      run: pip install --upgrade pip

    # Roda o script para enviar e-mail
    - name: Send Notification Email
      run: python send_email.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}  # Seu e-mail configurado como secret
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # Senha de app (não a senha comum)
        EMAIL_TO: ${{ secrets.EMAIL_TO }}  # Destinatário configurado como secret
